apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ServiceAccount
  - kratos.serviceaccount.yaml

  # ConfigMaps
  - kratos.configmap.yaml
  - kratos-identity-schema.configmap.yaml

  # Migration Job (PreSync hook)
  - kratos-migrate.job.yaml

  # Deployment и Service
  - kratos.deployment.yaml
  - kratos.service.yaml

  # Middleware и IngressRoute
  - kratos.middleware.yaml
  - kratos.ingressroute.yaml
