services:
  reverse-proxy:
    image: traefik:v3.6.2
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
      - --entrypoints.pg.address=:5432
      - --ping=true
      - --ping.entryPoint=traefik
    ports:
      - "80:80"
      - "8080:8080"  # dashboard + /metrics + /ping
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [appnet]
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik8080.entrypoints=traefik
      - traefik.http.routers.traefik8080.rule=PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      - traefik.http.routers.traefik8080.service=api@internal

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      # pass app DB params to init script
      DB_OWNERSHIP_MODE: ${DB_OWNERSHIP_MODE:-app_owner}
      PROJECT_DB: ${PROJECT_DB}
      PROJECT_DB_USER: ${PROJECT_DB_USER}
      PROJECT_DB_PASS: ${PROJECT_DB_PASS}
      HASURA_DB: ${HASURA_DB}
      HASURA_DB_USER: ${HASURA_DB_USER}
      HASURA_DB_PASS: ${HASURA_DB_PASS}
      KRATOS_DB: ${KRATOS_DB}
      KRATOS_DB_USER: ${KRATOS_DB_USER}
      KRATOS_DB_PASS: ${KRATOS_DB_PASS}
      HYDRA_DB: ${HYDRA_DB}
      HYDRA_DB_USER: ${HYDRA_DB_USER}
      HYDRA_DB_PASS: ${HYDRA_DB_PASS}
      TOLGEE_DB: ${TOLGEE_DB}
      TOLGEE_DB_USER: ${TOLGEE_DB_USER}
      TOLGEE_DB_PASS: ${TOLGEE_DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/00-init.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks: [appnet]
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.pg.rule=HostSNI(`*`)
      - traefik.tcp.routers.pg.entrypoints=pg
      - traefik.tcp.services.pg.loadbalancer.server.port=5432
      - traefik.tcp.routers.pg.tls=false
      - traefik.docker.network=appnet

  kratos:
    image: oryd/kratos:v25.4.0
    command: ["serve", "-c", "/etc/config/kratos.yml", "--dev", "--watch-courier"]
    environment:
      DSN: postgres://${KRATOS_DB_USER}:${KRATOS_DB_PASS}@postgres:5432/${KRATOS_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
      KRATOS_SELFSERVICE_DEFAULT_BROWSER_RETURN_URL: http://portal.localhost/
    volumes:
      - ./ory/kratos/kratos.yml:/etc/config/kratos.yml:ro
      - ./ory/kratos/identities/default.schema.json:/etc/config/kratos/identities/default.schema.json:ro
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    networks: [ appnet ]
    labels:
      - traefik.enable=true

      # public API Kratos (браузер, @ory/nextjs)
      - traefik.http.routers.kratos-public.rule=Host(`${KRATOS_PUBLIC_HOST}`)
      - traefik.http.routers.kratos-public.entrypoints=web
      - traefik.http.services.kratos-public.loadbalancer.server.port=4433

      # admin API Kratos (используется Oathkeeper, dev-инструменты)
      - traefik.http.routers.kratos-admin.rule=Host(`${KRATOS_ADMIN_HOST}`)
      - traefik.http.routers.kratos-admin.entrypoints=web
      - traefik.http.services.kratos-admin.loadbalancer.server.port=4434

  hydra:
    image: oryd/hydra:v25.4.0
    command: ["serve", "all", "--config", "/etc/config/hydra.yml", "--dev"]
    environment:
      DSN: postgres://${HYDRA_DB_USER}:${HYDRA_DB_PASS}@postgres:5432/${HYDRA_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
      # В проде лучше пробрасывать через env, но для PoC достаточно так
      SECRETS_SYSTEM: ${HYDRA_SYSTEM_SECRET}
    volumes:
      - ./ory/hydra/hydra.yml:/etc/config/hydra.yml:ro
    depends_on:
      postgres:
        condition: service_started
      hydra-migrate:
        condition: service_completed_successfully
    networks: [ appnet ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.hydra-public.rule=Host(`${HYDRA_PUBLIC_HOST}`)
      - traefik.http.routers.hydra-public.entrypoints=web
      - traefik.http.services.hydra-public.loadbalancer.server.port=4444

      # admin endpoint (для управления клиентами, introspection для Oathkeeper и т.п.)
      - traefik.http.routers.hydra-admin.rule=Host(`${HYDRA_ADMIN_HOST}`)
      - traefik.http.routers.hydra-admin.entrypoints=web
      - traefik.http.services.hydra-admin.loadbalancer.server.port=4445

  oathkeeper:
    image: oryd/oathkeeper:v25.4.0
    command:
      - serve
      - --config=/etc/oathkeeper/config.yml
    volumes:
      - ./ory/oathkeeper/config.yml:/etc/oathkeeper/config.yml:ro
      - ./ory/oathkeeper/access-rules.yml:/etc/oathkeeper/access-rules.yml:ro
    environment:
      LOG_LEVEL: debug
    depends_on:
      reverse-proxy:
        condition: service_started
    networks: [ appnet ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-gw.rule=Host(`${API_GATEWAY_HOST}`)
      - traefik.http.routers.api-gw.entrypoints=web
      - traefik.http.services.api-gw.loadbalancer.server.port=4455

  hasura:
    image: hasura/graphql-engine:v2.48.6
    depends_on:
      postgres:
        condition: service_healthy
#      kratos:
#        condition: service_started
#      hydra:
#        condition: service_started
#      hasura-wait:
#        condition: service_completed_successfully
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${HASURA_DB}
      HASURA_GRAPHQL_DATABASE_URL: postgres://${HASURA_DB_USER}:${HASURA_DB_PASS}@postgres:5432/${HASURA_DB}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
#      HASURA_GRAPHQL_JWT_SECRETS: |
#        [{"type":"RS256","jwk_url":"http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs","audience":"${KEYCLOAK_AUDIENCE}"}]
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_ENABLED_APIS: graphql,metadata,config,pgdump,metrics
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: "true"
      PG_PROJECT_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${PROJECT_DB}
    networks: [appnet]
    labels:
      - traefik.enable=true
      - traefik.http.routers.hasura.rule=Host(`${HASURA_HOST}`)
      - traefik.http.services.hasura.loadbalancer.server.port=8080

#  hasura-wait:
#    image: alpine:3.20
##    depends_on:
##      kratos:
##        condition: service_started
##      hydra:
##        condition: service_started
#    entrypoint: [ "sh", "-lc",
#                  "until wget -q --spider http://keycloak:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs; do echo '[hasura-wait] JWKS not ready; retrying...'; sleep 2; done" ]
#    networks: [ appnet ]
#    restart: "no"

  hasura-metadata:
    image: alpine:3.20
    depends_on:
      hasura:
        condition: service_started
    environment:
      HASURA_URL: http://hasura:8080
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
    volumes:
      - ./hasura/metadata:/metadata:ro
    entrypoint: ["sh","-lc","(command -v curl >/dev/null 2>&1 || apk add --no-cache curl) && /metadata/apply.sh"]
    restart: "no"
    networks: [appnet]

  kratos-migrate:
    image: oryd/kratos:latest
    command: ["migrate", "sql", "-e", "--yes"]
    environment:
      DSN: postgres://${KRATOS_DB_USER}:${KRATOS_DB_PASS}@postgres:5432/${KRATOS_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./ory/kratos/kratos.yml:/etc/config/kratos.yml:ro
      - ./ory/kratos/identities/default.schema.json:/etc/kratos/identities/default.schema.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks: [ appnet ]

  hydra-migrate:
    image: oryd/hydra:v2.2.0
    command:
      - migrate
      - sql
      - -e
      - --yes
    environment:
      DSN: postgres://${HYDRA_DB_USER}:${HYDRA_DB_PASS}@postgres:5432/${HYDRA_DB}?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      postgres:
        condition: service_healthy
    networks: [ appnet ]
    restart: "no"

  mailhog:
    image: mailhog/mailhog:latest
    networks: [ appnet ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog.rule=Host(`${MAILHOG_HOST}`)
      - traefik.http.services.mailhog.loadbalancer.server.port=8025
    ports:
      - "1025:1025"

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 25
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "True"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks: [appnet]
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`${PGADMIN_HOST}`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

  tolgee:
    image: tolgee/tolgee:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TOLGEE_POSTGRES_AUTOSTART_ENABLED: false
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${TOLGEE_DB}
      SPRING_DATASOURCE_USERNAME: ${TOLGEE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${TOLGEE_DB_PASS}
      TOLGEE_AUTHENTICATION_INITIAL_USERNAME: ${TOLGEE_ADMIN_USER}
      TOLGEE_AUTHENTICATION_INITIAL_PASSWORD: ${TOLGEE_ADMIN_PASS}
      SPRING_CONFIG_ADDITIONAL_LOCATION: file:/config.yaml
    volumes:
      - tolgee_data:/data
      - ./tolgee/config.yaml:/config.yaml:ro
    networks: [appnet]
    restart: no
    labels:
      - traefik.enable=true
      - traefik.http.routers.tolgee.rule=Host(`${TOLGEE_HOST}`)
      - traefik.http.routers.tolgee.entrypoints=web
      - traefik.http.services.tolgee.loadbalancer.server.port=8080

  arch-repo:
    build:
      context: ../packages/backend/apps/arch-repo-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PG_HOST: ${POSTGRES_ENDPOINT}
      PG_PORT: ${PG_PORT}
      PROJECT_DB: ${PROJECT_DB}
      PROJECT_DB_USER: ${PROJECT_DB_USER}
      PROJECT_DB_PASS: ${PROJECT_DB_PASS}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O- http://localhost:3000/healthz || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 60
    networks: [ appnet ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.arch-repo.rule=Host(`${ARCH_REPO_HOST}`)
      - traefik.http.services.arch-repo.loadbalancer.server.port=3000
    profiles: [ "backend" ]

  hasura-repo-sync:
    build:
      context: ../packages/hasura-repo-sync
      dockerfile: Dockerfile
    depends_on:
      arch-repo:
        condition: service_healthy
      hasura:
        condition: service_healthy
    environment:
      HASURA_ENDPOINT: ${HASURA_ENDPOINT}
      HASURA_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_SOURCE: ${HASURA_SOURCE}
      HASURA_SCHEMA: ${HASURA_SCHEMA}
      HASURA_UNTRACK_ITEMS: ${HASURA_UNTRACK_ITEMS}
      HASURA_RENAME_COLUMNS_CAMELCASE: ${HASURA_RENAME_COLUMNS_CAMELCASE}
    restart: "no"
    networks: [ appnet ]
    profiles: [ "backend" ]

  portal:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -lc "
        corepack enable &&
        pnpm i --frozen-lockfile &&
        pnpm dev
      "
    environment:
      NODE_ENV: development
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_HASURA_GRAPHQL_ENDPOINT: http://${HASURA_HOST}/v1/graphql
      NEXT_PUBLIC_CMS_URL: http://${STRAPI_HOST}
      KEYCLOAK_ISSUER: http://${AUTH_HOST}/realms/${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_AUDIENCE}
      WATCHPACK_POLLING: "true"
    volumes:
      - ../portal:/app
      - portal_node_modules:/app/node_modules
      - portal_pnpm_store:/root/.local/share/pnpm/store
    networks: [ appnet ]
    labels:
      - traefik.enable=true
      - traefik.http.routers.portal.rule=Host(`${PORTAL_HOST}`)
      - traefik.http.services.portal.loadbalancer.server.port=3000
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [ "app" ]

networks:
  appnet:

volumes:
  pgdata:
  pgadmin_data:
  tolgee_data:
  portal_node_modules:
  portal_pnpm_store:
