apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-partial-import
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "48"
data:
  partial-import.json: |
    {
      "ifResourceExists": "OVERWRITE",
      "roles": {
        "realm": [
          { "name": "ARCHITECT" },
          { "name": "DIRECTORY_MANAGER" },
          { "name": "VIEWER" }
        ]
      }
    }
  groups.json: |
    [
      { "name": "ADMIN" },
      { "name": "USER" }
    ]
