apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-partial-import
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "48"
data:
  partial-import.json: |
    {
      "ifResourceExists": "OVERWRITE",
      "roles": {
        "realm": [
          { "name": "CHIEF_ARCHITECT" },
          { "name": "ENTERPRISE_ARCHITECT" },
          { "name": "SOLUTION_ARCHITECT" },
          { "name": "SECURITY_ARCHITECT" },
          { "name": "INFRASTRUCTURE_ARCHITECT" }
        ]
      }
    }
  groups.json: |
    [
      { "name": "ADMIN" },
      { "name": "USER" }
    ]
