apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-pv
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Не указываем storageClassName, чтобы PV привязался напрямую к PVC
  # storageClassName: hostpath
  hostPath:
    path: /var/lib/k8s-data/grafana
    type: DirectoryOrCreate
  # Привязываем PV к PVC вручную
  claimRef:
    name: grafana-storage
    namespace: monitoring
