apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ServiceAccount
  - oathkeeper.serviceaccount.yaml

  # ConfigMaps
  - oathkeeper.configmap.yaml
  - oathkeeper-access-rules.configmap.yaml

  # Deployment и Service
  - oathkeeper.deployment.yaml
  - oathkeeper.service.yaml

  # Middleware и IngressRoute
  - oathkeeper.middleware.yaml
  - oathkeeper.ingressroute.yaml
