apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oathkeeper
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.archpad.pro`)
      kind: Rule
      services:
        - name: oathkeeper
          port: 4455
  tls:
    secretName: wildcard-archpad-pro-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: oathkeeper-http
  namespace: secure
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.archpad.pro`)
      kind: Rule
      services:
        - name: oathkeeper
          port: 4455
      middlewares:
        - name: redirect-to-https
          namespace: secure
