apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portal
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portal.archpad.pro`)
      kind: Rule
      services:
        - name: portal
          port: 3000
  tls:
    secretName: wildcard-archpad-pro-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portal-http
  namespace: platform
  annotations:
    argocd.argoproj.io/sync-wave: "75"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portal.archpad.pro`)
      kind: Rule
      services:
        - name: portal
          port: 3000
      middlewares:
        - name: redirect-to-https
          namespace: traefik
