apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD Applications для всех компонентов платформы
  # Эти Applications управляются отдельно от platform-root,
  # чтобы избежать конфликтов SharedResourceWarning
  - ../traefik/traefik.app.yaml
  - ../vault/vault.app.yaml
  - ../hasura/hasura.app.yaml
  - ../mailpit/mailpit.app.yaml
  - ../pgadmin/pgadmin.app.yaml
  - ../tolgee/tolgee.app.yaml
  - ../ory/kratos.app.yaml
  - ../ory/hydra.app.yaml
  - ../ory/oathkeeper.app.yaml
